name: Codespell

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  schedule:
    - cron: '23 4 * * 2'
  workflow_dispatch: {}

permissions:
  contents: read

jobs:
  spellcheck:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Run codespell
        uses: codespell-project/actions-codespell@v2
        with:
          check_filenames: true
          check_hidden: true
          ignore_words_list: crate,fo,teh,nd,ba,NumPy,PyTorch,TensorFlow,GitHub,GitHubActions,DevOps,DSA,Arch,Kubernetes,Nginx,MySQL,Anaconda,Matplotlib,scikit,PyPI,Flutter,Kotlin,Cassandra
          path: .
          skip: .git,**/node_modules/**,**/vendor/**
