name: Link Checker

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  schedule:
    - cron: '37 2 * * 3'
  workflow_dispatch: {}

permissions:
  contents: read

jobs:
  lychee:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Run lychee link checker
        uses: lycheeverse/lychee-action@v2
        with:
          args: >-
            --no-progress
            --accept 200,206,429
            --exclude-all-private
            --exclude-mail
            --exclude-tel
            --exclude-file .lycheeignore
            **/*.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
