name: Metrics

on:
  schedule:
    - cron: '11 1 * * *'
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Generate metrics
        uses: lowlighter/metrics@v4
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: Aryan10N
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Asia/Kolkata
          filename: metrics.svg
          output_action: commit
          committer_message: "chore(metrics): update metrics.svg"
          plugin_isocalendar: yes
          plugin_languages: yes
          plugin_languages_ignored: >-
            html, css
          plugin_languages_details: percentage
          plugin_languages_limit: 8
          plugin_followup: yes
          plugin_followup_sections: repositories
          plugin_stars: yes
          plugin_stars_limit: 3
